spring:
  kafka:
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
    consumer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      group-id: library-events-listener-group
    admin:
      properties:
        bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
